### ISSUE TITLE
Simplify backend config a bit

### ISSUE THREAD

**Issue by joerunde** [caikit/caikit#102]
## Is your feature request related to a problem? Please describe.

- The `disable_local` flag adds fun complexity, we can instead simplify the config and the code that configures backends by including `LOCAL` in the base config. Users can merge in more backends and keep local, or override the backends completely to remove it
- The `name` field of backends is also a bit extra, we don't have any current uses for a `name` field, so the behavior of allowing multiple backends of the same type but failing if they don't have unique names is a bit confusing when the names are unused.

## Describe the solution you'd like

- Merge / override semantics of lists so that we can remove the `disable_local` flag
- Support backend lists like:
```
load_priority:
  - type: TGIS
    config: 
      url: foo
  - type: TGIS
    config: 
      url: bar
```
