### ISSUE TITLE
Add a way to generically configure and infer resource requirements for tasks

### ISSUE THREAD

**Issue by kellyaa** [caikit/caikit#494]
## Is your feature request related to a problem? Please describe.

Some tasks may require different resource requirements than others. For example, prompt tuning a small model may require 1 GPU, where as fine-tuning a very large model may require more than 1 GPU. Currently in caikit, there is no way to express this so that backends that are running this task can make informed scheduling decisions.

## Describe the solution you'd like

Caikit is and should continue to be agnostic about the details of tasks that it is running. So we need a solution that can be adaptable and flexible to whatever task is running. A first thought that was brainstormed with @gabe-l-hart and @gkumbhat is having a runtime config that keys off of kwargs and the admin can associate resource requirements. For example:

```
config:
    resource_mapping:
        - kwargs:
            base_model: google/flan-t5-xl
            module: PeftFineTuning
          resources:
            gpu: 4
            memory: 1234
        - kwargs:
            base_model: bigdata/bloom-560m
            foo: baz
          resources:
            gpu: 1
            memory: 123
```

In the example we don't have to restrain ourselves to hard resource requests such as GPUs, but it could be other things like resource group labels, or whatever generic label the backend servicing the requests understands.
